# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
     user_manager:
            class:  AppBundle\Services\UserManager
            arguments: ["@doctrine.orm.entity_manager"]

     post_manager:
            class: AppBundle\Services\PostManager
            arguments: ["@doctrine.orm.entity_manager"]

# security servises ( api_key_user_provider and apikey_authenticator)
     api_key_user_provider:
            class: AppBundle\Security\ApiKeyUserProvider
            arguments: ["@doctrine.orm.entity_manager"]

     apikey_authenticator:
            class: AppBundle\Security\ApiKeyAuthenticator
            public: false
    # end security servises